### ISSUE TITLE
Warning on PHP 7.3

### ISSUE THREAD

**Issue by vinhtvu2** [UCF/UCF-Meeting-CPT-Plugin#2]
Warning: Use of undefined constant UCF_DEGREE__PLUGIN_URL - assumed 'UCF_DEGREE__PLUGIN_URL' (this will throw an Error in a future version of PHP) in /var/www/eduldr/wordpress/wp-content/plugins/UCF-Meeting-CPT/ucf-meeting.php on line 15

**Comment by jmbarne3** [comment]
Corrected in 0b53ac5e9ef8985c44087b8771cdd06edd28562b prior to initial release.
